GET http://localhost:5000/users

###

DELETE http://localhost:5000/friends/user2

###
GET http://localhost:5000/friends

###
GET http://localhost:5000/notes/user
###

GET http://localhost:5000/notes
###

POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "bruno",
    "password": "testowehaslo2005"
}

###

DELETE http://localhost:5000/notes/6

###

POST http://localhost:5000/notes
Content-Type: application/json

{
    "title": "bruno test note",
    "contents": "bruno test content"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "name": "nie bruno",
    "password": "pass"
}