GET http://localhost:5000/users

###

GET http://localhost:5000/notes
###

POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "bruno",
    "password": "pass"
}

###


POST http://localhost:5000/notes
Content-Type: application/json

{
    "title": "bruno test note",
    "contents": "bruno test content"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "name": "bruno",
    "password": "pass"
}