GET http://localhost:5000/users

###

GET http://localhost:5000/avatar

###
GET http://localhost:5000/friends-requests/bruno2005
###

###
POST http://localhost:5000/party/user1
###
GET http://localhost:5000/party/bruno2005
###
DELETE http://localhost:5000/party/32/bruno_2005

###
POST http://localhost:5000/friends/bruno2005

###
###
GET http://localhost:5000/friends/bruno_2005

###
GET http://localhost:5000/notes/user
###

GET http://localhost:5000/notes
###

POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "bruno",
    "password": "testowehaslo2005"
}

###

DELETE http://localhost:5000/notes/6

###

POST http://localhost:5000/notes
Content-Type: application/json

{
    "title": "bruno test note",
    "contents": "bruno test content"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "name": "bruno2005",
    "password": "pass"
}